name: Debug Server

on: workflow_dispatch

jobs:
  deploy:
    # runs-on: ubuntu-18.04
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: CD Into Build Directory
        run: cd www
        
    #  - name: Build
    #    run: hugo serve --theme changelog-theme

    #  - name: Deploy
    #    uses: peaceiris/actions-gh-pages@v3
    #    with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}
    #      publish_dir: ./www
      - name: Downloading Ngrok.
        run: |
           Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
           Invoke-WebRequest https://raw.githubusercontent.com/AtlasFn/atlas-server/main/start.bat -OutFile start.bat
      - name: Extracting Ngrok Files.
        run: Expand-Archive ngrok.zip
      - name: Connecting to your Ngrok account.
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Activating RDP access.
        run: | 
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          # copy wallpaper.jpg D:\a\wallpaper.jpg
          # copy wallpaper.bat D:\a\wallpaper.bat
      - name: Creating Tunnel.
        run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
      - name: Connecting to your RDP.
        run: cmd /c start.bat
      - name: RDP is ready!
        run: | 
          Invoke-WebRequest https://github.com/AtlasFn/atlas-server/raw/main/loop.ps1 -OutFile loop.ps1
          ./loop.ps1
