name: Hugo Server

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    # runs-on: ubuntu-18.04
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: CD Into Build Directory
        run: cd www
        
      - name: Build
        run: |
          cd www
          hugo serve --theme changelog-theme

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
